### ISSUE TITLE
[BUG] Illegal pyproject.toml section name

### ISSUE THREAD

**Issue by sinoroc** [s0undt3ch/setuptools-declarative-requirements#1]
@s0undt3ch You are not allowed to take ownership of the `requirements` section of `pyproject.toml` for your project:

* https://www.python.org/dev/peps/pep-0518/#tool-table

What you could do is use `[tool.setuptools-declarative-requirements]` since that is the _PyPI_ name of the project.

**Comment by s0undt3ch** [comment]
Honestly, I also think that, since this is trying to address the setuptools declarative config, the config should live in `setup.cfg` and not `pyproject.toml`.

**Comment by sinoroc** [comment]
> Honestly, I also think that, since this is trying to address the setuptools declarative config, the config should live in `setup.cfg` and not `pyproject.toml`.

Yes, that would make sense. I do not know what the policy is about taking ownership of section names in `setup.cfg`.

**Comment by stdedos** [comment]
I'd like if this was allowed to live _somewhere_ in `pyproject.toml`.

I'm doing active attempts to merge all <root> files _in one place_; the only thing I need in `setup.cfg` is `[requirements-files]` 😢

**Comment by sinoroc** [comment]
@stdedos This is possible in `setup.cfg` as well as in `pyproject.toml` since [*setuptools v62.6.0* released 2022-06-19](https://setuptools.pypa.io/en/latest/history.html#v62-6-0). No need for additional library.

But as before, think twice before doing this. Do not put indirect and/or pinned dependencies there. Package metadata should not contain indirect dependencies or pinned dependencies. https://github.com/pypa/setuptools/issues/1951#issuecomment-1430917786

***`pyproject.toml`***

```
[project]
# ...
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
# ...
dependencies = requirements.txt
```

***`setup.cfg`***

```
[options]
install_requires = file: requirements.txt
```
