### ISSUE TITLE
The requirements file 'requirements.txt' does not exist

### ISSUE THREAD

**Issue by abcfy2** [s0undt3ch/setuptools-declarative-requirements#5]
Here is my setup.cfg:

```ini
[metadata]
name = xg9900-data-service
version = 0.0.1

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6

[requirements-files]
install_requires = requirements.txt
```

Infact `requirements.txt` exists. But when I use `python -m build`:

```sh
Installing collected packages: setuptools, wheel, setuptools-declarative-requirements
Successfully installed setuptools-57.1.0 setuptools-declarative-requirements-1.2.0 wheel-0.36.2
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
You should consider upgrading via the '/tmp/build-env-9sxh7slt/bin/python -m pip install --upgrade pip' command.
The requirements file 'requirements.txt' does not exist

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```

What's wrong ?

**Comment by adamcunnington** [comment]
I'm encountering the same issue. @s0undt3ch any ideas? This wasn't an issue a short while back so I guess something in the ecosystem has changed?

**Comment by glensc** [comment]
Happens for me too. I was wondering should I put the requirements to subdir or package dir?

reproducer (as of [a86e05f](https://github.com/Taxel/PlexTraktSync/pull/263/commits/a86e05f4785eaa14c41afa60cd6bff6edb7357ee) commit -- may be outdated if looked very later than now):
- https://github.com/Taxel/PlexTraktSync/pull/263

**Comment by glensc** [comment]
a temporary workaround is to use absolute paths:

```sh
sed -i -e "s;install_requires = ;& $(pwd)/;" setup.cfg
```

**Comment by glensc** [comment]
It can be workarounded by skipping building of wheel:

```
python3 -m build -s
```

in other words, error is from wheel build process.

**Comment by glensc** [comment]
Ok. solved, problem was that requirements.txt was not included in sdist, but it's needed for building wheel.

so my fix was this:
- https://github.com/Taxel/PlexTraktSync/pull/263/commits/b8a0efa334579073353d771d9a0bbe27d4fd1f5a

this probably needs to be documented in project readme.

**Comment by adamcunnington-gdt** [comment]
Amazing! Good spot, thank you.

**Comment by s0undt3ch** [comment]
Yes, the requirements files must be included both in sdist and wheel packages.

Closing.

Please reopen if need be.

**Comment by glensc** [comment]
Is this documented now so people don't end up back to as at least three developers here did?

**Comment by stdedos** [comment]
... 4 now

**Comment by s0undt3ch** [comment]
It's documented now https://github.com/s0undt3ch/setuptools-declarative-requirements/commit/a0796c6c4a22c2d04a9ae35a0da109cb7e79cb1f
